# Generated by Django 3.2.5 on 2023-08-25 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_value', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accent_colors', models.ManyToManyField(related_name='accent_palettes', to='palettes.Color')),
                ('dominant_colors', models.ManyToManyField(related_name='dominant_palettes', to='palettes.Color')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaletteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accent_colors', models.ManyToManyField(related_name='accent_revisions', to='palettes.Color')),
                ('dominant_colors', models.ManyToManyField(related_name='dominant_revisions', to='palettes.Color')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='palettes.colorpalette')),
            ],
        ),
    ]
