# Generated by Django 3.2.5 on 2023-08-25 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palettes', '0002_remove_paletterevision_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palettes.colorpalette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
